### ISSUE TITLE
Submit sitemap in console

### ISSUE THREAD

**Issue by mcarcagente** [wpugph/dctx-website#101]
sitemap_index.xml

**Comment by WarenGonzaga** [comment]
@eabquina and @mcarcagente is this issue still active?

**Comment by mcarcagente** [comment]
@WarenGonzaga okay na sir nakapagsubmit na. Thanks

**Comment by WarenGonzaga** [comment]
@mcarcagente pwede na close to?

**Comment by mcarcagente** [comment]
@WarenGonzaga pwede na sir. try ko iclose alam ko kasi di ako pwede mag close naka restricted parin kasi ako pati sa pagcreate ng branch and etc. kahit naka public repo. at kapag di naclose paki close nalang po Salamat
