### ISSUE TITLE
Yoast Error on LIVE disabling EDITs for Pages

### ISSUE THREAD

**Issue by eabquina** [wpugph/dctx-website#131]
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'blog_id' in 'field list' in /srv/bindings/f6d61300f8a14701adf5333197b9ed0a/code/web/wp-content/plugins/wordpress-seo/vendor_prefixed/j4mie/idiorm/idiorm.php:464
Stack trace:
#0 /srv/bindings/f6d61300f8a14701adf5333197b9ed0a/code/web/wp-content/plugins/wordpress-seo/vendor_prefixed/j4mie/idiorm/idiorm.php(464): PDOStatement->execute()
#1 /srv/bindings/f6d61300f8a14701adf5333197b9ed0a/code/web/wp-content/plugins/wordpress-seo/vendor_prefixed/j4mie/idiorm/idiorm.php(1983): YoastSEO_Vendor\ORM::_execute('INSERT INTO `wp...', Array, 'default')
#2 /srv/bindings/f6d61300f8a14701adf5333197b9ed0a/code/web/wp-content/plugins/wordpress-seo/src/orm/yoast-model.php(662): YoastSEO_Vendor\ORM->save()
#3 /srv/bindings/f6d61300f8a14701adf5333197b9ed0a/code/web/wp-content/plugins/wordpress-seo/src/models/indexable.php(160): Yoast\WP\SEO\ORM\Yoast_Model->save()
#4 /srv/bindings/f6d61300f8a14701adf5333197b9ed0a/code/web/wp-content/plugins/wordpress-se in /srv/bindings/f6d61300f8a14701adf5333197b9ed0a/code/web/wp-content/plugins/wordpress-seo/vendor_prefixed/j4mie/idiorm/idiorm.php on line 464

**Comment by WarenGonzaga** [comment]
@eabquina I'm gonna close this since it is fixed and merged.
