### ISSUE TITLE
Remove "Join the Fight" section

### ISSUE THREAD

**Issue by carl-alberto** [wpugph/dctx-website#25]
<img width="996" alt="Screen Shot 2020-04-02 at 11 52 14 AM" src="https://user-images.githubusercontent.com/5098765/78208994-71400380-74d8-11ea-9ae4-54cc6719a43d.png">

**Comment by kennyalmendral** [comment]
@jraborar you forgot to remove the file named volunteer.php under the partials folder and please remove the styling associated with it in the style.css file.

**Comment by jraborar** [comment]
Thanks @carl-alberto is onboarding me on the workflow and will check those files.

**Comment by WarenGonzaga** [comment]
Is this fix? Can we close this? @carl-alberto @jraborar @kennyalmendral
