### ISSUE TITLE
Update "partner" section

### ISSUE THREAD

**Issue by carl-alberto** [wpugph/dctx-website#31]
From

<img width="890" alt="Screen Shot 2020-04-02 at 12 04 13 PM" src="https://user-images.githubusercontent.com/5098765/78209622-232bff80-74da-11ea-8554-67b92dea6111.png">

To

<img width="878" alt="Screen Shot 2020-04-02 at 12 04 06 PM" src="https://user-images.githubusercontent.com/5098765/78209626-258e5980-74da-11ea-9e5c-7a766ab9ea6c.png">

Will need to get respective logos

**Comment by WarenGonzaga** [comment]
For secuna logo and icons... please use this...
https://secuna.io/press-kit
