### ISSUE TITLE
/logmein page not redirecting to Admin page after successful login.

### ISSUE THREAD

**Issue by eabquina** [wpugph/dctx-website#44]
Update: I deactivated WP All In One Security, and everything worked well after.

I assume there is a conflict between the composer based structure of the site, versus the default behavior of WP All In One Security

**Comment by kennyalmendral** [comment]
Hello @eabquina I tried to replicate this issue and didn't encounter it, I reactivated the **WP All In One Security** plugin and tried logging in and it redirected me to the WP dashboard...

https://dev-dctx1.pantheonsite.io/logmein/

**Comment by WarenGonzaga** [comment]
@kennyalmendral same issue... di nag reredirect... is it because of WP All In One Security Plugin?

**Comment by eabquina** [comment]
@kennyalmendral @WarenGonzaga  

Yeah agree, we don't see it na in LIVE after we did the de-activate and reactivate. 

Same behavior too when done as staging branch (where it was still happening just a while ago)
https://staging-dctx1.pantheonsite.io

Closing this, marking workaround to be deactivate and reactivate the plugin. The assumption is that doing so somehow resets any stored paths or config prior to the composer set-up
