### ISSUE TITLE
GA Analytics not working. No Traffic data

### ISSUE THREAD

**Issue by eabquina** [wpugph/dctx-website#80]
No traffic data received for the site

**Comment by eabquina** [comment]
No data traffic also for mock GA URL sample created (dctx.techops.ph)

Reverting this now now

**Comment by WarenGonzaga** [comment]
@eabquina may I know the GA tracking code?

**Comment by eabquina** [comment]
bro @WarenGonzaga  Tracking code is **UA-162125973-1**
I saw in Slack its working na. Right now we actually have two scripts running on the page... the one from CAOS plugin, and the one added manually via header.php  

We might need to ask Mike so we can document here which one should stay and makes it work.

**Comment by WarenGonzaga** [comment]
@eabquina thanks! Do I need to do something about this?

**Comment by mcarcagente** [comment]
Hi team, here's the correct tracking script via header.php for GA. Thank you

 
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-162125973-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-162125973-1');
</script>

**Comment by eabquina** [comment]
thanks @mcarcagente , marking as closed na
